### Create new capability
POST http://localhost:3000/capability
Content-Type: application/json

{
    "name": "asdf",
    "category": 1
}

### Get all capabilities
GET http://localhost:3000/capability

### Get a capability by id
GET http://localhost:3000/capability/id/6

### Get capability by name
GET http://localhost:3000/capability/name/Data

### Delete a capability by id
DELETE http://localhost:3000/capability/9

### Update a capability
PATCH http://localhost:3000/capability/5
Content-Type: application/json

{
    "name": "Design"
}