### Create new badge
POST http://localhost:3000/badge
Content-Type: application/json

{
    "name": "New Badge2",
    "icon": "javascript_advanced.png",
    "image": "javascript_advanced.png",
    "skill": 2,
    "badgeType": 2
}

### Get all badges
GET http://localhost:3000/badge

### Get a badge by id
GET http://localhost:3000/badge/id/1

### Delete a badge by id
DELETE http://localhost:3000/badge/4

### Update a badge
PATCH http://localhost:3000/badge/1
Content-Type: application/json

{
    "name": "JavaScript Advanced",
    "skill": 1,
    "badgeType": 1,
    "icon": null,
    "image": null
}
