### Create new skill
POST http://localhost:3000/skill
Content-Type: application/json

{
    "name": "Java",
    "capability": 1,
    "skilllevel": 1
}

### Get all skills
GET http://localhost:3000/skill

### Get a skill by id
GET http://localhost:3000/skill/id/5

### Get all skills for a given capabillity
GET http://localhost:3000/skill/capability/1

### Get all skills of a given skill level
GET http://localhost:3000/skill/skilllevel/1

### Get skill by name
GET http://localhost:3000/skill/name/Beginner

### Delete a skill by id
DELETE http://localhost:3000/skill/7

### Update a skill
PATCH http://localhost:3000/skill/5
Content-Type: application/json

{
    "name": "Java Spring"
}