### Create new skilllevel
POST http://localhost:3000/skilllevel
Content-Type: application/json

{
    "name": "Expert"
}

### Get all skilllevels
GET http://localhost:3000/skilllevel

### Get a skilllevel by id
GET http://localhost:3000/skilllevel/id/2

### Get skilllevel by name
GET http://localhost:3000/skilllevel/name/Beginner

### Delete a skilllevel by id
DELETE http://localhost:3000/skilllevel/8

### Update a skilllevel
PATCH http://localhost:3000/skilllevel/5
Content-Type: application/json

{
    "name": "Expert"
}